language: node_js
node_js:
- '7'
notifications:
  email: false
  webhooks:
    urls:
    - https://server.tyratox.ch/webhooks/travis/
    on_success: always
    on_failure: always
    on_start: never
    on_cancel: never
    on_error: always
env:
  global:
    - CM_MESSAGE="Automated travis build"
    - secure: "IYm6hUv94Tk7wirtN+1PCoYfF+dCS3pBINcbQmh2Ijr7dUboAfazokyruoOu8AwFqi+JPTN5VJhhd7q9TLcpWX/V/P63TB9Kh/6H+gUuWyYbaMx9pN2+kDDERyfebAJ2v5hpxLO7qijMdF8fKdSNBKZaTO6EpYUJtr+np8XEuFBypXWJpjDElYsIh/P/2tWTYv7NwtjRT/ps9K44XHTZcTV5zCMuMqeHI8iw12xR7qH66Lpvhux7RtO+Se34yCaa/zra/k/d2OXz/O2LKRBULImLn3vf4f9N1v88aKyn0xV52XJHFdOTZLIl4+5HNEI1KLpIdYuENTGI88HexPgRaAEMKU/Jhmi+oI3ZcTZXQi8fJu+jqDH/raXERyH3wk/hT0PCtwA9X/gSMrOCU6jasXqAeAj1Dsb9PoTd9VsEtWTsA8QgGcTQQ5xkO7uyxn6A3cjbUgsX5s78haYA9GvIgiMZgRUtOmahp3kVXzWZy4IALzG6kJRGTf7f89EjPQTIq3TEA5UZ+TCD+bni+zrltRkmkOHzKz0klX9bqQpTv6BJy71MIoQRVs7eEbqr/NaXsShaPOyv7uTfvempClf+ek0bpGT645Lm+FGt+ndGmjU+9dl7fDk1Sg8Z4qSYFMssVF1m/k9r9ftOVNJl5ob6PCpzoGnU/5g6T8lM9/CwMvI="
branches:
  except:
  - "/^build-[0-9A-z\\-]*/"
before_install:
  - if [ "$TRAVIS_COMMIT_MESSAGE" = "$CM_MESSAGE" ]; then exit 0; fi
install:
- yarn install
before_script:
- if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "release" ]; then
    echo "{\"API_URL:\":\"https://api.booki.me\", \"API_VERSION:\":\"1\", \"CLIENT_ID:\":\"2\", \"REDIRECT_URI:\":\"https://booki.me/oauth-callback\"}" > config.json;
  fi
- if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then
    echo "{\"API_URL:\":\"https://beta-api.booki.me\", \"API_VERSION:\":\"1\", \"CLIENT_ID:\":\"2\", \"REDIRECT_URI:\":\"https://beta.booki.me/oauth-callback\"}" > config.json;
  fi
- if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "dev" ]; then
    echo "{\"API_URL:\":\"https://dev-api.booki.me\", \"API_VERSION:\":\"1\", \"CLIENT_ID:\":\"2\", \"REDIRECT_URI:\":\"https://dev.booki.me/oauth-callback\"}" > config.json;
  fi
- yarn test
script:
- yarn run build
after_success:
- cd build && find . -type d -print
- export GIT_TAG=build-$TRAVIS_BRANCH-$(date -u "+%Y-%m-%d")-$TRAVIS_BUILD_NUMBER
- git remote add origin-dashboard https://${GH_TOKEN}@github.com/hexcodech/booki-dashboard.git > /dev/null 2>&1
- git config --global user.email "builds@travis-ci.org"
- git config --global user.name "Travis CI"
- git config --global push.default simple
- git commit -a -m "$CM_MESSAGE"
- if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" == "release" ]; then
    git tag $GIT_TAG -a -m "Generated tag from Travis CI build $TRAVIS_BUILD_NUMBER";
    git push --quiet origin-dashboard HEAD:$TRAVIS_BRANCH $GIT_TAG > /dev/null 2>&1;
  else
    git push origin-dashboard HEAD:$TRAVIS_BRANCH;
  fi
